dist: xenial
language: node_js
node_js: 14
cache: npm
branches:
    only:
        - master
        - /^pluggable-widgets-tools-v*/
env:
    global:
        # Build only touched packages for pull requests when no shared files were touched
        - CHANGED_GLOBAL_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -v "^packages")
        - PARTIAL_BUILD=$(if [ "$CHANGED_GLOBAL_FILES" = "" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "true"; else echo "false"; fi)
        # Set arguments so lerna only runs scripts in changed packages
        - SINCE_ARG=$(if [ "$PARTIAL_BUILD" = "true" ]; then echo "--since $TRAVIS_BRANCH"; else echo ""; fi)
stages:
    - name: test
      if: tag IS blank
    - name: deploy
      if: tag IS present
jobs:
    fast_finish: true
    include:
        - name: "Lint"
          script:
              - npm run lint -- $SINCE_ARG
        - name: "Build on Linux"
          script:
              - npm run build -- $SINCE_ARG
        - name: "Run unit tests"
          script:
              - npm run test -- $SINCE_ARG
        - name: "Cross-platform tests (Node 10, windows)"
          node_js: 10
          os: windows
          script:
              - npm run test:cross-platform -- $SINCE_ARG
        - name: "Cross-platform tests (Node 10, linux)"
          node_js: 10
          script:
              - npm run test:cross-platform -- $SINCE_ARG
        - name: "Cross-platform tests (Node latest, windows)"
          os: windows
          script:
              - npm run test:cross-platform -- $SINCE_ARG
        - name: "Cross-platform tests (Node latest, linux)"
          script:
              - npm run test:cross-platform -- $SINCE_ARG
        - name: "Run end-to-end tests"
          dist: trusty
          addons:
              firefox: latest
          services:
              - xvfb
          before_install:
              - export DISPLAY=:99.0
              - sh -e /etc/init.d/xvfb start
              - sleep 3
          script:
              - npm run test:e2e -- $SINCE_ARG
          after_script:
              - if [[ "$TRAVIS_TEST_RESULT" -gt 0 ]]; then echo "Not works"; else echo "Works"; fi
        - stage: deploy
          name: "Release tools npm package"
          script:
              - echo "Ready to deploy!"
          before_deploy:
              - cd packages-common/pluggable-widgets-tools
          deploy:
              skip_cleanup: true
              provider: npm
              email: $NPM_EMAIL
              api_key: $NPM_KEY
              on:
                  tags: true
notifications:
    slack:
        on_cancel: never
        on_error: always
        on_failure: always
        secure: DjpkK0j6qCssXhI8Ym/pPQ9L+vQU8RMjaIhYmkNHDgKQIPifQib1nIDpUSVFWmCq/A+0cihu514MVvrFKE5rpg99QmwXTBsR0+KGG6wJrBXrBpxjndL4T8vqVvnpaOWU1k8Ky1ECdbfsHmkEUzk97JoekifvFr9k7g4bQyEtZufh4Y3L5UD9DSM6Q+AbR9tp7E/mUNyncB71VStscHDSv5MAD2uHmfn9PtyO3PQW2Y/YquhdR3lWi7GcjuSjZYH4A3s5V9LejUNxTMt7klztpnWRP9zRvh3pBPnol1L8mIJO5bAHoxSVg/djFLxXb7RmhwsuzJApZGXiYK6I3zRUlf2cEN6sjuW/vvXPo6nferd6/lCl10GljuqAm4Fw7yGdbh7L6wlZtUrCzkNs3VJYScqkRv0sXs1+8xx35Ge3uJGr7DOLIsg/TgSOOBpegc3XARILHBra07iDqGGSdm5x3xM0aVpqEJhMYPOOBmT6pJ1GO5AQOKyYooNT+mpY5ZjSjr3rXmzlPDHNqd12Bn6SXFa2VWZ8fVcCh43tDHVDvsUXpPJPukbfRV+0oSzQKQ1+yjvAbZJpuvOnf/AI5ZK88HcrRPCi3h2Q4ryaIXRlDdDqRrHGphTAJxvYrAuJEEU3oCv1VAAAxd82zZfnzy8ERc7Ck6kd8HL71TCBc3T19TY=
